development:
  adapter: postgresql
  encoding: unicode
  database: jstech_development
  pool: 5
  host: localhost
  username: nkcr
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: jstech_production
  pool: 5
  host: localhost
  username: jstech
  password: 